name: lundahoj_dbt
version: 1.0.0
config-version: 2

profile: lundahoj_dbt

model-paths: ["models"]

models:
  lundahoj_dbt:
    +materialized: view
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
    incremental:
      +schema: marts
      +materialized: incremental

